debug connection

diff --git a/.github/workflows/per.yml b/.github/workflows/per.yml
--- a/.github/workflows/per.yml
+++ b/.github/workflows/per.yml
@@ -114,19 +114,19 @@ jobs:
         run: |
           resource_manager -l $max32655 $max32690 $nrf52840 minicircuits_rf_switch minicircuits_rcdat6000 --owner $GITHUB_REF
 
-      - name: Flash DUTs
-        # uses: Analog-Devices-MSDK/btm-ci-scripts/actions/ocdflash@per-integration
-        # with:
-        #   board:
-        #     ${{ steps.target_ids.outputs.max32655 }}
-        #     ${{ steps.target_ids.outputs.max32690 }}
-        #   project: BLE5_ctr
-        #   build: true
-        #   suppress_output: true
-        env:
-            max32655: ${{ steps.target_ids.outputs.max32655 }}
-            max32690: ${{ steps.target_ids.outputs.max32690 }}
-        run: |
+      # - name: Flash DUTs
+      #   # uses: Analog-Devices-MSDK/btm-ci-scripts/actions/ocdflash@per-integration
+      #   # with:
+      #   #   board:
+      #   #     ${{ steps.target_ids.outputs.max32655 }}
+      #   #     ${{ steps.target_ids.outputs.max32690 }}
+      #   #   project: BLE5_ctr
+      #   #   build: true
+      #   #   suppress_output: true
+      #   env:
+      #       max32655: ${{ steps.target_ids.outputs.max32655 }}
+      #       max32690: ${{ steps.target_ids.outputs.max32690 }}
+      #   run: |
 
 
       #     echo $max32655
@@ -149,40 +149,40 @@ jobs:
         run: |
 
       
-          set +e
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 1M --results results/per_dtm_results_1M)
-          dtm_1m=$?
+          # set +e
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 1M --results results/per_dtm_results_1M)
+          # dtm_1m=$?
 
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 2M --results results/per_dtm_results_2M)
-          dtm_2m=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 2M --results results/per_dtm_results_2M)
+          # dtm_2m=$?
 
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S2 --results results/per_dtm_results_S2 --num-packets 100)
-          dtm_s2=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S2 --results results/per_dtm_results_S2 --num-packets 100)
+          # dtm_s2=$?
 
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S8 --results results/per_dtm_results_S8 --num-packets 100)
-          dtm_s8=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S8 --results results/per_dtm_results_S8 --num-packets 100)
+          # dtm_s8=$?
 
 
-          if [[ $dtm_2m -ne 0 ]]; then
-            echo DTM 2M failure
-            overall=1
-          fi
-          if [[ $dtm_s2 -ne 0 ]]; then
-            echo DTM S2 failure
-            overall=1
-          fi
-          if [[ $dtm_s8 -ne 0 ]]; then
-            echo DTM S8 failure
-            overall=1
-          fi
+          # if [[ $dtm_2m -ne 0 ]]; then
+          #   echo DTM 2M failure
+          #   overall=1
+          # fi
+          # if [[ $dtm_s2 -ne 0 ]]; then
+          #   echo DTM S2 failure
+          #   overall=1
+          # fi
+          # if [[ $dtm_s8 -ne 0 ]]; then
+          #   echo DTM S8 failure
+          #   overall=1
+          # fi
 
-          if [[ $overall -eq 1 ]]; then
-            echo DTM Overall Failure!
-            exit -1
-          else
-            echo DTM Passed moving to connection
-          fi
-          set -e
+          # if [[ $overall -eq 1 ]]; then
+          #   echo DTM Overall Failure!
+          #   exit -1
+          # else
+          #   echo DTM Passed moving to connection
+          # fi
+          # set -e
 
           # Connection
           (cd $TEST_DIR/per && per_connection.py $MASTER $DUT $RESULTS_DIR)
@@ -204,42 +204,42 @@ jobs:
         run: |
 
           FULL_RESULTS_DIR=${{ env.FULL_RESULTS_DIR }}
-          #DTM
-          set -e
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 1M --results $FULL_RESULTS_DIR/per_dtm_results_1M)
-          dtm_1m=$?
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 2M --results $FULL_RESULTS_DIR/per_dtm_results_2M)
-          dtm_2m=$?
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S2 --results $FULL_RESULTS_DIR/per_dtm_results_S2 --num-packets 100)
-          dtm_s2=$?
-          (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S8 --results $FULL_RESULTS_DIR/per_dtm_results_S8 --num-packets 100)
-          dtm_s8=$?
+          # #DTM
+          # set -e
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 1M --results $FULL_RESULTS_DIR/per_dtm_results_1M)
+          # dtm_1m=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy 2M --results $FULL_RESULTS_DIR/per_dtm_results_2M)
+          # dtm_2m=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S2 --results $FULL_RESULTS_DIR/per_dtm_results_S2 --num-packets 100)
+          # dtm_s2=$?
+          # (cd $TEST_DIR/per && python3 per_heatmap.py $MASTER $DUT --phy S8 --results $FULL_RESULTS_DIR/per_dtm_results_S8 --num-packets 100)
+          # dtm_s8=$?
 
-          overall=0
-          if [[ $dtm_1m -ne 0 ]]; then
-            echo DTM 1M failure
-            overall=1
-          fi
-          if [[ $dtm_2m -ne 0 ]]; then
-            echo DTM 2M failure
-            overall=1
-          fi
-          if [[ $dtm_s2 -ne 0 ]]; then
-            echo DTM S2 failure
-            overall=1
-          fi
-          if [[ $dtm_s8 -ne 0 ]]; then
-            echo DTM S8 failure
-            overall=1
-          fi
+          # overall=0
+          # if [[ $dtm_1m -ne 0 ]]; then
+          #   echo DTM 1M failure
+          #   overall=1
+          # fi
+          # if [[ $dtm_2m -ne 0 ]]; then
+          #   echo DTM 2M failure
+          #   overall=1
+          # fi
+          # if [[ $dtm_s2 -ne 0 ]]; then
+          #   echo DTM S2 failure
+          #   overall=1
+          # fi
+          # if [[ $dtm_s8 -ne 0 ]]; then
+          #   echo DTM S8 failure
+          #   overall=1
+          # fi
 
-          if [[ $overall -eq 1 ]]; then
-            echo DTM Overall Failure!
-            exit -1
-          else
-            echo DTM Passed moving to connection
-          fi
-          set +e
+          # if [[ $overall -eq 1 ]]; then
+          #   echo DTM Overall Failure!
+          #   exit -1
+          # else
+          #   echo DTM Passed moving to connection
+          # fi
+          # set +e
 
           # Connection
           (cd $TEST_DIR/per && per_connection.py $MASTER $DUT $RESULTS_DIR)
